<a href="https://colab.research.google.com/github/Hesham-14/Neural-Network-Projects/blob/main/Word_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

In [2]:
corpus = [
          # Positive Reviews
          'this is an excellent movie',
          'the movie was fantastic I like it',
          'You should watch it is brilliant',
          'Exceptionally good',
          'Wonderfully directed and executed I like it so much',
          'Its a fantastic series',
          'Never watched such a brillent movie',
          'It is a Wonderful movie',

          # Negative Reviews

          'horrible acting',
          'waste of money',
          'pathetic picture',
          'It was very boring',
          'I did not like the movie',
          'the movie was horrible',
          'I will not recommend',
          'The acting is pathetic'
          ]

In [3]:
sentiments = array([1,1,1,1,1,1,1,1, 0,0,0,0,0,0,0,0])

In [4]:
# import NLTK "Natural Language Toolkit"
import nltk

nltk.download('punkt')
from nltk.tokenize import word_tokenize

all_words = []
for sent in corpus:
  tokenize_word = word_tokenize(sent)
  for word in tokenize_word:
    all_words.append(word)


unique_words = set(all_words)
print(len(unique_words))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
46


In [5]:
embedded_sentences = [one_hot(sent, 50) for sent in corpus]
print(embedded_sentences)

[[45, 5, 16, 14, 41], [48, 41, 11, 18, 27, 27, 32], [25, 13, 24, 32, 5, 42], [32, 18], [31, 44, 45, 32, 27, 27, 32, 24, 18], [28, 11, 18, 2], [6, 13, 1, 11, 1, 41], [32, 5, 11, 31, 41], [40, 31], [11, 26, 24], [49, 24], [32, 11, 1, 19], [27, 41, 6, 27, 48, 41], [48, 41, 11, 40], [27, 36, 6, 25], [48, 31, 5, 49]]


In [6]:
word_count = lambda sentence: len(word_tokenize(sentence))
longest_sentence = max(corpus, key=word_count)
length_long_sentence = len(word_tokenize(longest_sentence))

In [7]:
padded_sentences = pad_sequences(embedded_sentences, length_long_sentence, padding='post')
print(padded_sentences)

[[45  5 16 14 41  0  0  0  0]
 [48 41 11 18 27 27 32  0  0]
 [25 13 24 32  5 42  0  0  0]
 [32 18  0  0  0  0  0  0  0]
 [31 44 45 32 27 27 32 24 18]
 [28 11 18  2  0  0  0  0  0]
 [ 6 13  1 11  1 41  0  0  0]
 [32  5 11 31 41  0  0  0  0]
 [40 31  0  0  0  0  0  0  0]
 [11 26 24  0  0  0  0  0  0]
 [49 24  0  0  0  0  0  0  0]
 [32 11  1 19  0  0  0  0  0]
 [27 41  6 27 48 41  0  0  0]
 [48 41 11 40  0  0  0  0  0]
 [27 36  6 25  0  0  0  0  0]
 [48 31  5 49  0  0  0  0  0]]


In [8]:
model = Sequential()
model.add(Embedding(50, 20, input_length=length_long_sentence))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.summary()

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['acc'])

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 9, 20)             1000      
_________________________________________________________________
flatten (Flatten)            (None, 180)               0         
_________________________________________________________________
dense (Dense)                (None, 1)                 181       
Total params: 1,181
Trainable params: 1,181
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.fit(padded_sentences, sentiments, epochs=100, verbose=1)

Epoch 1/100
1/1 [==============================] - 1s 856ms/step - loss: 0.6862 - acc: 0.6875
Epoch 2/100
1/1 [==============================] - 0s 9ms/step - loss: 0.6834 - acc: 0.7500
Epoch 3/100
1/1 [==============================] - 0s 7ms/step - loss: 0.6805 - acc: 0.8125
Epoch 4/100
1/1 [==============================] - 0s 4ms/step - loss: 0.6777 - acc: 0.8125
Epoch 5/100
1/1 [==============================] - 0s 4ms/step - loss: 0.6749 - acc: 0.8125
Epoch 6/100
1/1 [==============================] - 0s 5ms/step - loss: 0.6720 - acc: 0.8125
Epoch 7/100
1/1 [==============================] - 0s 5ms/step - loss: 0.6692 - acc: 0.8125
Epoch 8/100
1/1 [==============================] - 0s 4ms/step - loss: 0.6664 - acc: 0.8125
Epoch 9/100
1/1 [==============================] - 0s 5ms/step - loss: 0.6635 - acc: 0.8125
Epoch 10/100
1/1 [==============================] - 0s 8ms/step - loss: 0.6607 - acc: 0.8750
Epoch 11/100
1/1 [==============================] - 0s 5ms/step - loss: 0.657

In [11]:
loss, accuracy = model.evaluate(padded_sentences, sentiments, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 93.750000
